### ISSUE TITLE
Make model-index available on conda-forge

### ISSUE THREAD

**Issue by giswqs** [paperswithcode/model-index#5]
It would be great to make model-index available on conda-forge. Otherwise, downstream packages of model-index can't be made available on conda-forge. Making it available on conda-forge will benefit all downstream packages and numerous conda-forge users. 

It appears that model-index depends on the alias package modelindex. However, the source code of modelindex is not available on GitHub. It is impossible to build the conda-forge recipe for modelidex.
https://github.com/paperswithcode/modelindex-alias

Relevant issues: 

- https://github.com/autogluon/autogluon/issues/612
- https://github.com/open-mmlab/mim/issues/193

@arturdaraujo @zhouzaida

**Comment by arturdaraujo** [comment]
Yes! These guys seem to be the maintainers of this package
@rstojnic @RJT1990 @datumbox

**Comment by arturdaraujo** [comment]
@rstojnic @RJT1990 @datumbox

**Comment by datumbox** [comment]
@arturdaraujo Sorry but I can't help you on this one. I'm not a maintainer of the package.

**Comment by arturdaraujo** [comment]
If we may be able to create a PR to make a package optional (which is a package they doesn't really do anything, just an alias package called modelindex) 

This would make it possible for us to publish on conda forge

**Comment by arturdaraujo** [comment]
After that we are able to publish ourselves this package on conda forge. 

There are quite a few big packages downstream that depends on this package

**Comment by arturdaraujo** [comment]
I sent an email to the organization responsible for the package model-index paperswithcode (https://github.com/paperswithcode) to see if we get a response.
"
Hello,

I and a group of people who are trying to publish your package on conda-forge are facing some issues. I'm not sure if you are familiar with conda but to do this we have to have all the packages used by model-index published on conda-forge to publish model-index itself.

The problem is this: the "model-index" package has a "modelindex" package (an alias package it seems). So at the moment, we CAN'T PUBLISH this modelindex on conda-forge because there is no GitHub page, only on PyPI! 

We suggest this: I and the others are going to create a Pull Request to change modelindex to optional or remove it entirely from model-index, as this alias package doesn't really do anything. If you are comfortable with that we will proceed. After this we will be able to publish your package. 

This will make this package available to everyone on conda-forge (millions of people) and also help many other projects publish their own. 

Artur
"

**Comment by giswqs** [comment]
model-index is now available on conda-forge. 
https://anaconda.org/conda-forge/model-index
